name: Publish Avro
on:
  push:
    branches:
      - main
    paths:
      - 'idl/**'
env:
  AVRO_VERSION: 1.11.0
  AVRO_MIRROR: https://apache.zero.com.ar/avro
  GITHUB_REPOSITORY_OWNER: architecture-it
  BUILD_CONFIGURATION: 'Release'
  DIRECORY_SRC: 'lang/csharp/Andreani/wilgab/Events' # working directory remplace {appname}
  IDL_FOLDER: 'idl/' # archivo avdl remplace {Example}
  EVENT: 'Pedido'
  OUTPUT_DIRECTORY: 'bin/Release/'
jobs:
  gen-nuget:
    name: "Generate Libs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          path: ./origin
      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jre # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: actions/setup-go@v2
        with:
          version: 1.17.7
      - name: Get Avro Tools
        run: wget --quiet ${{env.AVRO_MIRROR}}/avro-${{env.AVRO_VERSION}}/java/avro-tools-${{env.AVRO_VERSION}}.jar
      - name: Get gogen-avro Tools
        run: go get github.com/actgardner/gogen-avro/v10/cmd/...
      # - name: ls
      #   run: ls
      # - name: setting source
      #   run: cd origin/
      # - name: ls
      #   run: ls 
      # - name: ls
      #   run: ls origin/
      - name: Generate Protocol
        run: java -jar avro-tools-${{env.AVRO_VERSION}}.jar idl2schemata origin/${{env.IDL_FOLDER}}${{env.EVENT}}.avdl avro/
      - name: Generate folder output
        run: mkdir avro/struct
      - name: Generate go struct
        run: /home/runner/go/bin/gogen-avro avro/struct avro/${{env.EVENT}}.avsc
      - name: ls avro
        run: ls avro/
      - name: ls avro/struct
        run: ls avro/struct/
      - name: Checkout Nuget go
        uses: actions/checkout@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          repository: covaw/template-nuget-go
          # token: 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
          # token: ${{ secrets.ARQUITECTURA_DEPLOY }}
          token: ${{ env.GITHUB_TOKEN }}
          # key: ${{ secrets.SSH_PRIVATE_KEY }}
          # known_hosts: ${{ secrets.KNOWN_HOSTs }}
          path: ./nuget
      - name: ls current
        run: ls
      - name: ls nuget
        run: ls nuget/
      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{env.EVENT}}
      - name: Copy/Create file
        run: |
          FILE=avro/struct/${{steps.string.outputs.lowercase}}
          if [ -f "$FILE" ]; then
            echo "Copying $FILE"
            cp -R avro/struct/${{steps.string.outputs.lowercase}} ./nuget
          else 
            echo "Creating $FILE"
            touch ./nuget/${{steps.string.outputs.lowercase}}
          fi
      - name: ls nuget
        run: ls ./nuget/
      - name: GIT STATUS
        run: |
          cd ./nuget
          ls
      - name: Push Project B
        run: |
          cd ./nuget
          git config user.name "covaw"
          git config user.email "wcova@andreani.com"
          git config user.password "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"
          git add .
          git commit -am "Add Schema ${{env.EVENT}}"
          git push